server:
  port: 8000
spring:
  profiles:
    active: dev
  redis:
    #数据库索引
    database: ${REDIS_DB:0}
    host: ${REDIS_HOST:xxxxx}
    port: ${REDIS_PORT:6379}
    password: xxxxx
    #连接超时时间
    timeout: 5000
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path.windows},file:${web.upload-path.linux}
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.elblog.mapper

web:
  upload-path:
    windows: d:/uploadImage/
    linux: /home/elblog/uploadImage/
